name: coin_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0
  record: ^5.0.4
  path: ^1.8.0
  audioplayers: ^4.1.0
  http: ^0.13.6
  path_provider: ^2.1.1
  #pick and read file
  file_picker: ^6.1.1
  #open files
  open_file: ^3.3.2
  #snackbar
  awesome_snackbar_content: ^0.1.3


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cat.webp"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Merienda
      fonts:
      - asset: assets/fonts/Merienda-Medium.ttf
